/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\User\\Desktop\\scripthqs\\blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-08d3513d",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08d3513d").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-03e9926e",
    path: "/about/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-03e9926e").then(next)
    },
  },
  {
    path: "/about/index.html",
    redirect: "/about/"
  },
  {
    name: "v-aa272b92",
    path: "/frame/notes/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa272b92").then(next)
    },
  },
  {
    path: "/frame/notes/index.html",
    redirect: "/frame/notes/"
  },
  {
    name: "v-6ff5f4e5",
    path: "/frame/vue/vue2/02vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ff5f4e5").then(next)
    },
  },
  {
    name: "v-d7a36a2e",
    path: "/frame/vue/vue2/04vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7a36a2e").then(next)
    },
  },
  {
    name: "v-5dd9c9e3",
    path: "/frame/vue/vue2/01vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5dd9c9e3").then(next)
    },
  },
  {
    name: "v-fbdbc032",
    path: "/frame/vue/vue2/03vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fbdbc032").then(next)
    },
  },
  {
    name: "v-8f32be26",
    path: "/frame/vue/vue2/06vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8f32be26").then(next)
    },
  },
  {
    name: "v-b36b142a",
    path: "/frame/vue/vue2/05vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b36b142a").then(next)
    },
  },
  {
    name: "v-6afa6822",
    path: "/frame/vue/vue2/07vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6afa6822").then(next)
    },
  },
  {
    name: "v-46c2121e",
    path: "/frame/vue/vue2/08vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-46c2121e").then(next)
    },
  },
  {
    name: "v-2289bc1a",
    path: "/frame/vue/vue2/09vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2289bc1a").then(next)
    },
  },
  {
    name: "v-bd41abba",
    path: "/frame/vue/vue2/12vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd41abba").then(next)
    },
  },
  {
    name: "v-e17a01be",
    path: "/frame/vue/vue2/11vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e17a01be").then(next)
    },
  },
  {
    name: "v-7d26d41f",
    path: "/frame/vue/vue2/10vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d26d41f").then(next)
    },
  },
  {
    name: "v-990955b6",
    path: "/frame/vue/vue2/13vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-990955b6").then(next)
    },
  },
  {
    name: "v-5098a9ae",
    path: "/frame/vue/vue2/15vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5098a9ae").then(next)
    },
  },
  {
    name: "v-74d0ffb2",
    path: "/frame/vue/vue2/14vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74d0ffb2").then(next)
    },
  },
  {
    name: "v-795f1212",
    path: "/frame/vue/vue2/v_total.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-795f1212").then(next)
    },
  },
  {
    name: "v-61c3994e",
    path: "/frame/vue/vue2/vue_css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61c3994e").then(next)
    },
  },
  {
    name: "v-5c7cdc5d",
    path: "/frame/vue/vue2/vue_mixin.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c7cdc5d").then(next)
    },
  },
  {
    name: "v-136bcc76",
    path: "/frame/vue/vue3/vue3_01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-136bcc76").then(next)
    },
  },
  {
    name: "v-5acf3e43",
    path: "/frame/vue/vue2/vue_proxy.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5acf3e43").then(next)
    },
  },
  {
    name: "v-fb5b338a",
    path: "/frame/vue/vuer/vue_r.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fb5b338a").then(next)
    },
  },
  {
    name: "v-ffa19b7a",
    path: "/frame/vue/vue3/vue3_02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ffa19b7a").then(next)
    },
  },
  {
    name: "v-0a144ac1",
    path: "/frame/vue/vue3/vue3_03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a144ac1").then(next)
    },
  },
  {
    name: "v-5d85354f",
    path: "/frame/vue/vuer/vueRouter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d85354f").then(next)
    },
  },
  {
    name: "v-77b54afe",
    path: "/net/ajax/02ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77b54afe").then(next)
    },
  },
  {
    name: "v-7e763150",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e763150").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-d562bec4",
    path: "/net/ajax/03ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d562bec4").then(next)
    },
  },
  {
    name: "v-7ec87391",
    path: "/frame/vue/vuex/vuex.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ec87391").then(next)
    },
  },
  {
    name: "v-5a1bf55e",
    path: "/net/ajax/01ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a1bf55e").then(next)
    },
  },
  {
    name: "v-5efd6844",
    path: "/net/ajax/05ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5efd6844").then(next)
    },
  },
  {
    name: "v-9a301384",
    path: "/net/ajax/04ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9a301384").then(next)
    },
  },
  {
    name: "v-54c065f1",
    path: "/frame/vue/vuer/vuer_total.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54c065f1").then(next)
    },
  },
  {
    name: "v-0bb3f71e",
    path: "/net/ajax/07ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0bb3f71e").then(next)
    },
  },
  {
    name: "v-23cabd04",
    path: "/net/ajax/06ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23cabd04").then(next)
    },
  },
  {
    name: "v-294d4cbe",
    path: "/net/ajax/08ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-294d4cbe").then(next)
    },
  },
  {
    name: "v-748a3a58",
    path: "/net/ajax/axios02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-748a3a58").then(next)
    },
  },
  {
    name: "v-5f7a17b4",
    path: "/net/db/01MongoDB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f7a17b4").then(next)
    },
  },
  {
    name: "v-6d6de2dc",
    path: "/net/ajax/axios03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d6de2dc").then(next)
    },
  },
  {
    name: "v-3c9db6a8",
    path: "/net/db/02MongoDB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c9db6a8").then(next)
    },
  },
  {
    name: "v-7ba691d4",
    path: "/net/ajax/axios01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ba691d4").then(next)
    },
  },
  {
    name: "v-ae0f0dac",
    path: "/net/db/03MongoDB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae0f0dac").then(next)
    },
  },
  {
    name: "v-15533bac",
    path: "/net/db/04MongoDB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-15533bac").then(next)
    },
  },
  {
    name: "v-1ea766a2",
    path: "/net/node/01express.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ea766a2").then(next)
    },
  },
  {
    name: "v-32e16544",
    path: "/net/node/01node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32e16544").then(next)
    },
  },
  {
    name: "v-0428a2fe",
    path: "/net/node/02node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0428a2fe").then(next)
    },
  },
  {
    name: "v-6d4219b4",
    path: "/net/node/03express.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d4219b4").then(next)
    },
  },
  {
    name: "v-5d935004",
    path: "/net/node/01exprss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d935004").then(next)
    },
  },
  {
    name: "v-74032ce4",
    path: "/net/node/02express.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74032ce4").then(next)
    },
  },
  {
    name: "v-21c1f89e",
    path: "/net/node/03node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21c1f89e").then(next)
    },
  },
  {
    name: "v-3f5b4e3e",
    path: "/net/node/04node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f5b4e3e").then(next)
    },
  },
  {
    name: "v-74167faa",
    path: "/net/node/05express.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74167faa").then(next)
    },
  },
  {
    name: "v-1ebab968",
    path: "/net/node/04express.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ebab968").then(next)
    },
  },
  {
    name: "v-5cf4a3de",
    path: "/net/node/05node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5cf4a3de").then(next)
    },
  },
  {
    name: "v-6d1b7428",
    path: "/net/node/06express.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d1b7428").then(next)
    },
  },
  {
    name: "v-7a8df97e",
    path: "/net/node/06node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a8df97e").then(next)
    },
  },
  {
    name: "v-517b5176",
    path: "/project/hqsui/grid.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-517b5176").then(next)
    },
  },
  {
    name: "v-947eb684",
    path: "/net/node/08node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-947eb684").then(next)
    },
  },
  {
    name: "v-73e315a8",
    path: "/project/hqsui/collapse.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73e315a8").then(next)
    },
  },
  {
    name: "v-07dab084",
    path: "/project/hqsui/input.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07dab084").then(next)
    },
  },
  {
    name: "v-453f6d44",
    path: "/project/hqsui/button.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-453f6d44").then(next)
    },
  },
  {
    name: "v-594c0b44",
    path: "/net/node/09node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-594c0b44").then(next)
    },
  },
  {
    name: "v-5e8dcc7a",
    path: "/project/hqsui/install/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e8dcc7a").then(next)
    },
  },
  {
    path: "/project/hqsui/install/index.html",
    redirect: "/project/hqsui/install/"
  },
  {
    name: "v-7c13b864",
    path: "/project/hqsui/popover.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c13b864").then(next)
    },
  },
  {
    name: "v-50c12524",
    path: "/project/hqsui/toast.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-50c12524").then(next)
    },
  },
  {
    name: "v-436b095e",
    path: "/project/utils/chapter1/01_install.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-436b095e").then(next)
    },
  },
  {
    name: "v-49e77f6e",
    path: "/project/hqsui/layout.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49e77f6e").then(next)
    },
  },
  {
    name: "v-bf9f99de",
    path: "/project/utils/chapter1/02_intro.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf9f99de").then(next)
    },
  },
  {
    name: "v-cc8dfdf4",
    path: "/project/hqsui/tabs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cc8dfdf4").then(next)
    },
  },
  {
    name: "v-0043ddf1",
    path: "/project/utils/chapter1/04_npm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0043ddf1").then(next)
    },
  },
  {
    name: "v-1839c53b",
    path: "/project/utils/chapter1/03_create.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1839c53b").then(next)
    },
  },
  {
    name: "v-30f7853b",
    path: "/project/utils/chapter2/02array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30f7853b").then(next)
    },
  },
  {
    name: "v-5c7a259e",
    path: "/project/utils/chapter2/04string.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5c7a259e").then(next)
    },
  },
  {
    name: "v-789eaf5e",
    path: "/project/utils/chapter2/03object.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-789eaf5e").then(next)
    },
  },
  {
    name: "v-236beb1e",
    path: "/project/utils/chapter2/01function.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-236beb1e").then(next)
    },
  },
  {
    name: "v-1bbe5331",
    path: "/project/utils/chapter2/07ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1bbe5331").then(next)
    },
  },
  {
    name: "v-10643971",
    path: "/project/utils/chapter2/05extend.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10643971").then(next)
    },
  },
  {
    name: "v-bea1808a",
    path: "/project/utils/chapter2/06bindEvent.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bea1808a").then(next)
    },
  },
  {
    name: "v-5626e891",
    path: "/project/utils/chapter2/09pubsub.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5626e891").then(next)
    },
  },
  {
    name: "v-5ffe549e",
    path: "/project/utils/chapter2/10promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ffe549e").then(next)
    },
  },
  {
    name: "v-4a656543",
    path: "/project/utils/chapter2/08event_bus.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a656543").then(next)
    },
  },
  {
    name: "v-3c8c2b26",
    path: "/project/vuecms/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3c8c2b26").then(next)
    },
  },
  {
    path: "/project/vuecms/index.html",
    redirect: "/project/vuecms/"
  },
  {
    name: "v-2fe625a4",
    path: "/tools/git/03git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fe625a4").then(next)
    },
  },
  {
    name: "v-111eaa6d",
    path: "/project/vuemall/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-111eaa6d").then(next)
    },
  },
  {
    path: "/project/vuemall/index.html",
    redirect: "/project/vuemall/"
  },
  {
    name: "v-aa5ea178",
    path: "/tools/git/02git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aa5ea178").then(next)
    },
  },
  {
    name: "v-3a111264",
    path: "/tools/git/05git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a111264").then(next)
    },
  },
  {
    name: "v-81b2ee78",
    path: "/tools/git/06git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81b2ee78").then(next)
    },
  },
  {
    name: "v-6d5d14f8",
    path: "/tools/git/08git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d5d14f8").then(next)
    },
  },
  {
    name: "v-443bff24",
    path: "/tools/git/07git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-443bff24").then(next)
    },
  },
  {
    name: "v-9608c7f8",
    path: "/tools/git/04git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9608c7f8").then(next)
    },
  },
  {
    name: "v-4e66ebe4",
    path: "/tools/git/09git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e66ebe4").then(next)
    },
  },
  {
    name: "v-8381cfb8",
    path: "/tools/git/10git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8381cfb8").then(next)
    },
  },
  {
    name: "v-43548e84",
    path: "/tools/git/11git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43548e84").then(next)
    },
  },
  {
    name: "v-5ad61cb8",
    path: "/tools/git/14git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ad61cb8").then(next)
    },
  },
  {
    name: "v-57aa6804",
    path: "/tools/git/15git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57aa6804").then(next)
    },
  },
  {
    name: "v-0f0bb48e",
    path: "/tools/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f0bb48e").then(next)
    },
  },
  {
    path: "/tools/git/index.html",
    redirect: "/tools/git/"
  },
  {
    name: "v-6f2bf638",
    path: "/tools/git/12git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f2bf638").then(next)
    },
  },
  {
    name: "v-ea09574a",
    path: "/tools/nat/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ea09574a").then(next)
    },
  },
  {
    path: "/tools/nat/index.html",
    redirect: "/tools/nat/"
  },
  {
    name: "v-5b97e024",
    path: "/tools/webpack/01webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b97e024").then(next)
    },
  },
  {
    name: "v-324c6238",
    path: "/tools/webpack/03webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-324c6238").then(next)
    },
  },
  {
    name: "v-4d7f7b44",
    path: "/tools/git/13git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d7f7b44").then(next)
    },
  },
  {
    name: "v-721bbda4",
    path: "/tools/webpack/05webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-721bbda4").then(next)
    },
  },
  {
    name: "v-bd8e50f8",
    path: "/tools/webpack/02webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bd8e50f8").then(next)
    },
  },
  {
    name: "v-2c7ac644",
    path: "/tools/webpack/04webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c7ac644").then(next)
    },
  },
  {
    name: "v-42fea3c4",
    path: "/tools/webpack/08webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42fea3c4").then(next)
    },
  },
  {
    name: "v-0544a738",
    path: "/tools/webpack/07webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0544a738").then(next)
    },
  },
  {
    name: "v-908695f8",
    path: "/tools/webpack/06webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-908695f8").then(next)
    },
  },
  {
    name: "v-55adc504",
    path: "/web/css/css10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55adc504").then(next)
    },
  },
  {
    name: "v-44342504",
    path: "/web/css/01css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44342504").then(next)
    },
  },
  {
    name: "v-bcd79238",
    path: "/web/css/css11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bcd79238").then(next)
    },
  },
  {
    name: "v-eec0c9b8",
    path: "/tools/webpack/09webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-eec0c9b8").then(next)
    },
  },
  {
    name: "v-39611aa4",
    path: "/web/css/css13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-39611aa4").then(next)
    },
  },
  {
    name: "v-250aae78",
    path: "/web/css/css12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-250aae78").then(next)
    },
  },
  {
    name: "v-1d147044",
    path: "/web/css/css16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d147044").then(next)
    },
  },
  {
    name: "v-68fae224",
    path: "/web/css/css17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68fae224").then(next)
    },
  },
  {
    name: "v-f570e6f8",
    path: "/web/css/css14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f570e6f8").then(next)
    },
  },
  {
    name: "v-00c7c5e4",
    path: "/web/css/css19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00c7c5e4").then(next)
    },
  },
  {
    name: "v-963d57f8",
    path: "/web/css/css18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-963d57f8").then(next)
    },
  },
  {
    name: "v-f2d4e1b8",
    path: "/web/css/css20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f2d4e1b8").then(next)
    },
  },
  {
    name: "v-1e6272e4",
    path: "/web/css/css22.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e6272e4").then(next)
    },
  },
  {
    name: "v-c2079438",
    path: "/web/css/css2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c2079438").then(next)
    },
  },
  {
    name: "v-93a152b8",
    path: "/web/css/css24.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-93a152b8").then(next)
    },
  },
  {
    name: "v-2736c922",
    path: "/web/css/css3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2736c922").then(next)
    },
  },
  {
    name: "v-a11d4740",
    path: "/web/css/css4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a11d4740").then(next)
    },
  },
  {
    name: "v-5da40338",
    path: "/web/css/css15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5da40338").then(next)
    },
  },
  {
    name: "v-37abef9e",
    path: "/web/css/css5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37abef9e").then(next)
    },
  },
  {
    name: "v-4821161a",
    path: "/web/css/css7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4821161a").then(next)
    },
  },
  {
    name: "v-8032fa48",
    path: "/web/css/css6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8032fa48").then(next)
    },
  },
  {
    name: "v-6a48e4c4",
    path: "/web/css/css23.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a48e4c4").then(next)
    },
  },
  {
    name: "v-c8e01f60",
    path: "/web/css/less.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c8e01f60").then(next)
    },
  },
  {
    name: "v-5f48ad50",
    path: "/web/css/css8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f48ad50").then(next)
    },
  },
  {
    name: "v-58963c96",
    path: "/web/css/css9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-58963c96").then(next)
    },
  },
  {
    name: "v-7efb9ce2",
    path: "/web/css/scss.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7efb9ce2").then(next)
    },
  },
  {
    name: "v-f0b61d80",
    path: "/web/css/reflow.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f0b61d80").then(next)
    },
  },
  {
    name: "v-81952338",
    path: "/web/css/css_tip.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-81952338").then(next)
    },
  },
  {
    name: "v-33f92678",
    path: "/web/css/total.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33f92678").then(next)
    },
  },
  {
    name: "v-7ffe645e",
    path: "/web/html/02html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ffe645e").then(next)
    },
  },
  {
    name: "v-1e603b94",
    path: "/web/html/01web.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e603b94").then(next)
    },
  },
  {
    name: "v-65ca82de",
    path: "/web/html/04code.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65ca82de").then(next)
    },
  },
  {
    name: "v-c4d08c04",
    path: "/web/html/03html.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4d08c04").then(next)
    },
  },
  {
    name: "v-f47b8844",
    path: "/web/html/06ul.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f47b8844").then(next)
    },
  },
  {
    name: "v-04e89844",
    path: "/web/html/05div.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04e89844").then(next)
    },
  },
  {
    name: "v-3789b828",
    path: "/web/html/09a.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3789b828").then(next)
    },
  },
  {
    name: "v-65276f4e",
    path: "/web/html/07table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65276f4e").then(next)
    },
  },
  {
    name: "v-cdd99a84",
    path: "/web/html/08form.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cdd99a84").then(next)
    },
  },
  {
    name: "v-101fb1fe",
    path: "/web/html/10font.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-101fb1fe").then(next)
    },
  },
  {
    name: "v-44fa9418",
    path: "/web/html/13total.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44fa9418").then(next)
    },
  },
  {
    name: "v-5f7ed24a",
    path: "/web/html/12html5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f7ed24a").then(next)
    },
  },
  {
    name: "v-6a08bb54",
    path: "/web/html/11img.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a08bb54").then(next)
    },
  },
  {
    name: "v-764ee069",
    path: "/web/js/js1/jsa01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-764ee069").then(next)
    },
  },
  {
    name: "v-79dd0c27",
    path: "/web/js/js1/jsa02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-79dd0c27").then(next)
    },
  },
  {
    name: "v-fe0d38ba",
    path: "/web/js/js1/jsa04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fe0d38ba").then(next)
    },
  },
  {
    name: "v-7d6b37e5",
    path: "/web/js/js1/jsa03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d6b37e5").then(next)
    },
  },
  {
    name: "v-efd489c2",
    path: "/web/js/js1/jsa06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-efd489c2").then(next)
    },
  },
  {
    name: "v-e8b83246",
    path: "/web/js/js1/jsa07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8b83246").then(next)
    },
  },
  {
    name: "v-f6f0e13e",
    path: "/web/js/js1/jsa05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f6f0e13e").then(next)
    },
  },
  {
    name: "v-e19bdaca",
    path: "/web/js/js1/jsa08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e19bdaca").then(next)
    },
  },
  {
    name: "v-da7f834e",
    path: "/web/js/js1/jsa09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-da7f834e").then(next)
    },
  },
  {
    name: "v-3e0ffea6",
    path: "/web/js/js1/jsa10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e0ffea6").then(next)
    },
  },
  {
    name: "v-28baf832",
    path: "/web/js/js1/jsa13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-28baf832").then(next)
    },
  },
  {
    name: "v-219ea0b6",
    path: "/web/js/js1/jsa14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-219ea0b6").then(next)
    },
  },
  {
    name: "v-36f3a72a",
    path: "/web/js/js1/jsa11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36f3a72a").then(next)
    },
  },
  {
    name: "v-2fd74fae",
    path: "/web/js/js1/jsa12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2fd74fae").then(next)
    },
  },
  {
    name: "v-1a82493a",
    path: "/web/js/js1/jsa15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a82493a").then(next)
    },
  },
  {
    name: "v-1365f1be",
    path: "/web/js/js1/jsa16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1365f1be").then(next)
    },
  },
  {
    name: "v-052d42c6",
    path: "/web/js/js1/jsa18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-052d42c6").then(next)
    },
  },
  {
    name: "v-00f78a5b",
    path: "/web/js/js1/jsa19.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00f78a5b").then(next)
    },
  },
  {
    name: "v-0c499a42",
    path: "/web/js/js1/jsa17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c499a42").then(next)
    },
  },
  {
    name: "v-52bd786d",
    path: "/web/js/js1/jsa21.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52bd786d").then(next)
    },
  },
  {
    name: "v-4f2f4caf",
    path: "/web/js/js1/jsa20.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4f2f4caf").then(next)
    },
  },
  {
    name: "v-627125a3",
    path: "/web/js/js2/jsb02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-627125a3").then(next)
    },
  },
  {
    name: "v-1d4a5108",
    path: "/web/js/js2/event%20loop.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d4a5108").then(next)
    },
  },
  {
    path: "/web/js/js2/event loop.html",
    redirect: "/web/js/js2/event%20loop.html"
  },
  {
    path: "/web/js/js2/event loop.html",
    redirect: "/web/js/js2/event%20loop.html"
  },
  {
    name: "v-5ee2f9e5",
    path: "/web/js/js2/jsb01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ee2f9e5").then(next)
    },
  },
  {
    name: "v-6d1ba8dd",
    path: "/web/js/js2/jsb05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d1ba8dd").then(next)
    },
  },
  {
    name: "v-698d7d1f",
    path: "/web/js/js2/jsb04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-698d7d1f").then(next)
    },
  },
  {
    name: "v-65ff5161",
    path: "/web/js/js2/jsb03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65ff5161").then(next)
    },
  },
  {
    name: "v-77c62c17",
    path: "/web/js/js2/jsb08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77c62c17").then(next)
    },
  },
  {
    name: "v-74380059",
    path: "/web/js/js2/jsb07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-74380059").then(next)
    },
  },
  {
    name: "v-70a9d49b",
    path: "/web/js/js2/jsb06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-70a9d49b").then(next)
    },
  },
  {
    name: "v-7b5457d5",
    path: "/web/js/js2/jsb09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b5457d5").then(next)
    },
  },
  {
    name: "v-47771361",
    path: "/web/js/js3/jsc01.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47771361").then(next)
    },
  },
  {
    name: "v-6ce7cbae",
    path: "/web/js/js2/jsb10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ce7cbae").then(next)
    },
  },
  {
    name: "v-4e936add",
    path: "/web/js/js3/jsc03.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4e936add").then(next)
    },
  },
  {
    name: "v-4b053f1f",
    path: "/web/js/js3/jsc02.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4b053f1f").then(next)
    },
  },
  {
    name: "v-5221969b",
    path: "/web/js/js3/jsc04.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5221969b").then(next)
    },
  },
  {
    name: "v-55afc259",
    path: "/web/js/js3/jsc05.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55afc259").then(next)
    },
  },
  {
    name: "v-593dee17",
    path: "/web/js/js3/jsc06.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-593dee17").then(next)
    },
  },
  {
    name: "v-94a3413a",
    path: "/web/js/js3/jsc11.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-94a3413a").then(next)
    },
  },
  {
    name: "v-605a4593",
    path: "/web/js/js3/jsc08.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-605a4593").then(next)
    },
  },
  {
    name: "v-5ccc19d5",
    path: "/web/js/js3/jsc07.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ccc19d5").then(next)
    },
  },
  {
    name: "v-8d86e9be",
    path: "/web/js/js3/jsc12.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8d86e9be").then(next)
    },
  },
  {
    name: "v-9bbf98b6",
    path: "/web/js/js3/jsc10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9bbf98b6").then(next)
    },
  },
  {
    name: "v-63e87151",
    path: "/web/js/js3/jsc09.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63e87151").then(next)
    },
  },
  {
    name: "v-71158bce",
    path: "/web/js/js3/jsc16.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71158bce").then(next)
    },
  },
  {
    name: "v-7f4e3ac6",
    path: "/web/js/js3/jsc14.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f4e3ac6").then(next)
    },
  },
  {
    name: "v-866a9242",
    path: "/web/js/js3/jsc13.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-866a9242").then(next)
    },
  },
  {
    name: "v-69f93452",
    path: "/web/js/js3/jsc17.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69f93452").then(next)
    },
  },
  {
    name: "v-7831e34a",
    path: "/web/js/js3/jsc15.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7831e34a").then(next)
    },
  },
  {
    name: "v-62dcdcd6",
    path: "/web/js/js3/jsc18.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-62dcdcd6").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]